/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package email;

import datastructres.HashTable;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JOptionPane;
/**
 *
 * @author Badar Muneer
 */
public class SavedEmails extends javax.swing.JPanel {

    /**
     * Creates new form SavedEmails
     */
    private HashTable table;
    private List<String> list;
    public SavedEmails() 
    {
        table=new HashTable();
        list=new ArrayList<>();
        initComponents();
        fillTable();
    }
    
    public void fillTable()
    {
        try
        {
            Scanner input=new Scanner(new File("save-cont.txt"));
            String[] keyValue=new String[2];
            while(input.hasNext())
            {
                //System.out.println("Read:"+input.nextLine());
                keyValue=input.nextLine().split(",");
                table.put(keyValue[0],keyValue[1]);
            }
        
            input.close();
        }catch(FileNotFoundException e)
        {
            JOptionPane.showMessageDialog(this,e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainDisplayPanel = new javax.swing.JPanel();
        hintLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        nameSaveTextField = new javax.swing.JTextField();
        saveEmailAddress = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(753, 575));

        hintLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hintLabel.setText("Send Email to Saved Contacts:");

        searchTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchTextField.setForeground(java.awt.Color.gray);
        searchTextField.setText("Enter name here!");
        searchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusLost(evt);
            }
        });

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email/plus.png"))); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email/remove-user.png"))); // NOI18N
        jButton1.setText("Remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nameSaveTextField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        nameSaveTextField.setForeground(java.awt.Color.gray);
        nameSaveTextField.setText("Name");
        nameSaveTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameSaveTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameSaveTextFieldFocusLost(evt);
            }
        });

        saveEmailAddress.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        saveEmailAddress.setForeground(java.awt.Color.gray);
        saveEmailAddress.setText("Email Address");
        saveEmailAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                saveEmailAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                saveEmailAddressFocusLost(evt);
            }
        });

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email/add-contact.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainDisplayPanelLayout = new javax.swing.GroupLayout(mainDisplayPanel);
        mainDisplayPanel.setLayout(mainDisplayPanelLayout);
        mainDisplayPanelLayout.setHorizontalGroup(
            mainDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDisplayPanelLayout.createSequentialGroup()
                .addGroup(mainDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainDisplayPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainDisplayPanelLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(mainDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mainDisplayPanelLayout.createSequentialGroup()
                                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(113, 113, 113)
                                        .addComponent(jButton1))))))
                    .addGroup(mainDisplayPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(mainDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameSaveTextField)
                            .addComponent(saveEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)))
                    .addGroup(mainDisplayPanelLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(saveButton)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        mainDisplayPanelLayout.setVerticalGroup(
            mainDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(nameSaveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public List getList()
    {
        return list;
    }
    private void searchTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusGained
        // TODO add your handling code here:
        
        if(searchTextField.getText().equals("Enter name here!"))
        {
            searchTextField.setText("");
            searchTextField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchTextFieldFocusGained

    private void searchTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusLost
        // TODO add your handling code here:
        
        if(searchTextField.getText().equals(""))
        {
            searchTextField.setText("Enter name here!");
            searchTextField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_searchTextFieldFocusLost

    private void nameSaveTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameSaveTextFieldFocusGained
        // TODO add your handling code here:
        
        if(this.nameSaveTextField.getText().equals("Name"))
        {
            nameSaveTextField.setText("");
            nameSaveTextField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_nameSaveTextFieldFocusGained

    private void nameSaveTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameSaveTextFieldFocusLost
        // TODO add your handling code here:
        
        if(this.nameSaveTextField.getText().equals(""))
        {
            nameSaveTextField.setText("Name");
            nameSaveTextField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_nameSaveTextFieldFocusLost

    private void saveEmailAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_saveEmailAddressFocusGained
        // TODO add your handling code here:
        
        if(this.saveEmailAddress.getText().equals("Email Address"))
        {
            saveEmailAddress.setText("");
            saveEmailAddress.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_saveEmailAddressFocusGained

    private void saveEmailAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_saveEmailAddressFocusLost
        // TODO add your handling code here:
        
        if(this.saveEmailAddress.getText().equals(""))
        {
            saveEmailAddress.setText("Email Address");
            saveEmailAddress.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_saveEmailAddressFocusLost

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        FileWriter writer;
        String name="";
        String email="";
        
        try
        {
            if(this.saveEmailAddress.getText().equals("") || this.nameSaveTextField.getText().equals(""))
                return;
            
            else
            {
                name=nameSaveTextField.getText();
                email=saveEmailAddress.getText();
                table.put(name,email);
                writer=new FileWriter(new File("save-cont.txt"));
                //BufferedWriter buffer=new BufferedWriter(writer);
                writer.write(table.toString());
                saveEmailAddress.setText("");
                nameSaveTextField.setText("");
                
                writer.close();
                
                JOptionPane.showMessageDialog(this, "Successfully saved...","Saved",JOptionPane.INFORMATION_MESSAGE);
                
            }
        } catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(this, ex,"Error",JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(SavedEmails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(this.searchTextField.getText().equals(""))
        {
            return;
        }
        
        else
        {
            table.remove(searchTextField.getText());
            searchTextField.setText("");
            
            try
            {
                FileWriter writer=new FileWriter(new File("save-cont.txt"));
                writer.write(table.toString());
                writer.close();
            } 
            catch (IOException ex) 
            {
                JOptionPane.showMessageDialog(this,ex,"Error",JOptionPane.ERROR_MESSAGE);
                //Logger.getLogger(SavedEmails.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        
        if(!this.searchTextField.getText().equals(""))
        {
            String email=table.get(searchTextField.getText());
            if(email!=null)
            {
               list.add(email);
               JOptionPane.showMessageDialog(this,"Added");
               searchTextField.setText("");
               return;
            }
            JOptionPane.showMessageDialog(this,"Not Found");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    public void resetCount()
    {
        list.clear();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel mainDisplayPanel;
    private javax.swing.JTextField nameSaveTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField saveEmailAddress;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
